#!/usr/bin/env bash
# The run lock: live vs stale, as seen by the kit (lib/common.sh), the operator
# tool (tools/run-lock.sh) and the deploy hook (generated by 06-git-deploy.sh).
#
# Exists because the first trial aborted before its cleanup was installed, left
# the lock behind, and the hook then refused every push until it was removed by
# hand.
set -uo pipefail
# The bench and its lock are VM tools: GNU timeout/sed/stat, /proc. On macOS,
# skip (as the routing suite does) and run the whole suite with `make test-vm`.
if [ "$(uname -s)" != Linux ]; then
  echo "lock"
  echo "  skip  needs Linux (GNU timeout, sed, stat; /proc) -- run everything on the VM: make test-vm"
  echo; echo "all lock tests passed (skipped)"; exit 0
fi
KIT="$(cd "$(dirname "$0")/.." && pwd)"
SB="$(mktemp -d)"; trap 'kill $LIVE 2>/dev/null; rm -rf "$SB"' EXIT
export GVPN_STATE="$SB/state" GVPN_RUN_LOCK="$SB/state/run.lock"
mkdir -p "$SB/state/runs"
fail=0
ok()  { printf '  ok    %s\n' "$*"; }
bad() { printf '  FAIL  %s\n' "$*"; fail=1; }
echo "run lock"

# a process whose command line looks like a bench
bash -c 'exec -a "bash bench/gvpn-bench.sh" sleep 60' & LIVE=$!
sleep 0.3

lock() {  # lock NAME PID|none [finished]
  local d="$SB/state/runs/$1"; mkdir -p "$d"; rm -f "$d/bench.pid" "$d/finished.json"
  [ "$2" = none ] || echo "$2" > "$d/bench.pid"
  [ "${3:-}" = finished ] && echo '{}' > "$d/finished.json"
  ln -sfn "$d" "$GVPN_RUN_LOCK"
}
state() { ( . "$KIT/lib/common.sh"; gvpn_lock_state; echo "$GVPN_LOCK_STATE" ); }
expect() { local got; got="$(state)"; [ "$got" = "$1" ] && ok "kit:  $2 -> $1" || bad "kit:  $2 -> $got, want $1"; }

rm -f "$GVPN_RUN_LOCK";        expect none    "no lock"
lock a "$LIVE";                expect live    "bench alive"
lock b 999999;                 expect stale   "bench PID gone"
lock c "$$";                   expect stale   "PID reused by something that is not a bench"
lock d "$LIVE" finished;       expect stale   "run wrote finished.json"
lock e none;                   expect unknown "no owner recorded (a pre-bench.pid lock)"
ln -sfn "$SB/nowhere" "$GVPN_RUN_LOCK"; expect stale "run directory gone"

# --- tools/run-lock.sh
lock f "$LIVE"
bash "$KIT/tools/run-lock.sh" --clear >/dev/null; [ -L "$GVPN_RUN_LOCK" ] \
  && ok "tool: refuses to clear a live lock" || bad "tool: cleared a live lock"
lock g 999999
bash "$KIT/tools/run-lock.sh" --clear >/dev/null; [ -L "$GVPN_RUN_LOCK" ] \
  && bad "tool: left a stale lock" || ok "tool: clears a stale lock"
lock h none   # a bench-looking process is running, so an unowned lock is not provably stale
bash "$KIT/tools/run-lock.sh" --clear >/dev/null; [ -L "$GVPN_RUN_LOCK" ] \
  && ok "tool: keeps an unowned lock while a bench runs" || bad "tool: cleared an unowned lock while a bench runs"

# --- the deploy hook's own copy of the test
eval "$(awk '/^lock_check_sh\(\) \{/{on=1} on{print} on&&/^SH$/{sh=1} sh&&/^\}$/{exit}' "$KIT/setup/06-git-deploy.sh")"
lock_check_sh > "$SB/hook.sh" && printf '%s\n' 'lock_live && echo LIVE || echo DEPLOY' >> "$SB/hook.sh"
hook() { sh "$SB/hook.sh" 2>/dev/null; }
lock i "$LIVE";  [ "$(hook)" = LIVE ]   && ok "hook: refuses while the bench is alive" || bad "hook: deployed over a live bench"
lock j 999999;   [ "$(hook)" = DEPLOY ] && [ ! -L "$GVPN_RUN_LOCK" ] \
  && ok "hook: clears a dead bench's lock and deploys" || bad "hook: blocked by a dead bench's lock"
kill $LIVE 2>/dev/null; wait $LIVE 2>/dev/null
lock k none;     [ "$(hook)" = DEPLOY ] && ok "hook: an unowned lock with no bench running is cleared" \
  || bad "hook: blocked by an unowned lock with no bench running"

echo; [ "$fail" = 0 ] && echo "all lock tests passed" || echo "FAILURES above"; exit $fail
