#!/usr/bin/env bash
#
# use-arm.sh -- install one arm by hand; optionally connect and count routes.
#
#   sudo ./bench/use-arm.sh auto --count         # must read many routes
#   sudo ./bench/use-arm.sh pin-planner --count  # must read 1
#   sudo ./bench/use-arm.sh --show               # what is installed now
#   sudo ./bench/use-arm.sh --restore            # back to the network config
#
# Installing an arm = write its config to config-gvpn-arm.toml and re-point the
# config.toml symlink (lib/common.sh). If the service then fails to start, the
# original network config is put back and the service restarted, so this never
# leaves the node down.
set -euo pipefail
. "$(cd "$(dirname "$0")/.." && pwd)/lib/common.sh"

CTL="${GVPN_CTL:-gnosis_vpn-ctl}"
DEST="${GVPN_DESTINATION:-UK}"
SETTLE="${GVPN_COUNT_SETTLE:-90}"
READY_TIMEOUT=180; CONNECT_TIMEOUT=180
LEGACY="/etc/systemd/system/gnosisvpn.service.d/30-arm.conf /etc/gnosisvpn/hopr-arm.yaml"

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
# `status` prints the node state on line 1 and, after a `---`, the connection:
#   Ready (Node is running) - traffic: Good, gas: Good
#   ---
#   Connected to UK (since 12s)        | Connecting to UK (since 3s, phase ...)
# (gnosis_vpn-ctl/src/main.rs; strings from gnosis_vpn-lib command/mod.rs)
ctl_raw()    { timeout 10 "$CTL" -o plain status 2>/dev/null; }
ctl_status() { ctl_raw | head -1; }

show() {
  echo "  config.toml -> $(readlink -f "$GVPN_CONFIG_PATH")"
  head -1 "$GVPN_CONFIG_PATH" 2>/dev/null | grep -q 'GENERATED by gvpn-8408' \
    && sed -n '1s/.*-- /  arm:        /p' "$GVPN_CONFIG_PATH" \
    || echo "  arm:        <none -- the network config>"
  echo "  planner:"
  sed -n '/^\[connection\.path_planner\]/,/^\[/p' "$GVPN_CONFIG_PATH" 2>/dev/null \
    | grep -E '^[a-z_]+ *=' | sed 's/^/    /' || echo "    <preset>"
  echo "  service:    $(systemctl is-active gnosisvpn 2>/dev/null)   client: $(ctl_status || echo '<no answer>')"
}

usage() { sed -n '3,8p' "$0" | sed 's/^# \{0,1\}//'; echo; echo "arms in $GVPN_ARMS_DIR:"; ls "$GVPN_ARMS_DIR" 2>/dev/null | sed 's/^/  /'; }

ARM=""; COUNT=0
while [ $# -gt 0 ]; do
  case "$1" in
    --count)   COUNT=1; shift ;;
    --dest)    DEST="$2"; shift 2 ;;
    --settle)  SETTLE="$2"; shift 2 ;;
    --show)    show; exit 0 ;;
    --restore) gvpn_restore_original && gvpn_service_restart && { echo "network config restored"; show; exit 0; }
               echo "could not restore -- see: sudo ./tools/diagnose.sh" >&2; exit 1 ;;
    -h|--help) usage; exit 0 ;;
    -*)        echo "unknown option: $1" >&2; exit 2 ;;
    *)         ARM="$1"; shift ;;
  esac
done
[ -n "$ARM" ] || { usage; exit 2; }
[ "$(id -u)" = 0 ] || { echo "run with sudo" >&2; exit 1; }
ARM_DIR="$GVPN_ARMS_DIR/$ARM"
[ -f "$ARM_DIR/config.toml" ] || { echo "no arm '$ARM' -- run: sudo -E ./setup/02-make-arms.sh" >&2; exit 1; }

# ----------------------------------------------------------------- install --
say "installing arm: $ARM"
sed 's/^/    /' "$ARM_DIR/README"
if [ -f "$ARM_DIR/flags" ]; then
  for f in $(cat "$ARM_DIR/flags"); do
    systemctl show gnosisvpn -p ExecStart | grep -q -- "$f" \
      || { echo "    this arm needs service flag $f -- run: sudo ./setup/00-vm-setup.sh --allow-insecure" >&2; exit 1; }
  done
fi
[ -f "$ARM_DIR/PREREQUISITE" ] && { echo; echo "    PREREQUISITE:"; sed 's/^/      /' "$ARM_DIR/PREREQUISITE"; }

"$CTL" disconnect >/dev/null 2>&1 || true
rm -f $LEGACY                                   # left by kits before the config.toml fix
gvpn_install_arm "$ARM_DIR/config.toml"
log_from=$(stat -c %s "$GVPN_SERVICE_LOG" 2>/dev/null || echo 0)

if ! gvpn_service_restart; then
  say "SERVICE DID NOT START with this arm"
  gvpn_service_why | sed 's/^/    /'
  echo "    --- service log since install ---"
  tail -c +"$((log_from + 1))" "$GVPN_SERVICE_LOG" 2>/dev/null | tail -15 | sed 's/^/    /'
  say "restoring the network config"
  gvpn_restore_original && gvpn_service_restart \
    && echo "    service is back up on the network config" \
    || echo "    STILL DOWN -- run: sudo ./tools/diagnose.sh"
  exit 1
fi
echo "    service active"
[ "$COUNT" = 1 ] || { show; exit 0; }

# ------------------------------------------------------------------- count --
# One route vs many is the check that a pin actually took. It needs planner
# DEBUG logging (00-vm-setup.sh) and traffic flowing, or there is nothing to see.
say "counting routes for '$ARM' via $DEST  (~$((SETTLE / 60 + 3)) min, one line per state change)"
grep -qE "^\[destinations\.\"?$DEST\"?\]" "$GVPN_CONFIG_PATH" \
  || { echo "    '$DEST' is not a destination in this config" >&2; exit 1; }

log_errors() {  # the binary's own ERROR/WARN lines since the count began, plus known causes
  local new; new="$(tail -c +"$((log_from + 1))" "$GVPN_SERVICE_LOG" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g')"
  printf '%s\n' "$new" | grep -aE ' (ERROR|WARN) ' | tail -12 | sed 's/^/      /'
  if printf '%s\n' "$new" | grep -q 'rtnetlink.*Network unreachable (os error 101)'; then
    echo
    echo "    KNOWN CAUSE: the kernel refused the client's bypass route via the default"
    echo "    gateway (ENETUNREACH) -- the gateway is not on-link, so tunnel setup fails"
    echo "    and the worker restarts. Not the arm. Fix: sudo ./setup/00-vm-setup.sh"
  fi
}

# Poll until PATTERN matches the node or connection line. Stops early, with the
# evidence, if the node falls back to Initializing/Warmup after having been
# Ready: that is a node reset, and waiting it out only hides the cause.
wait_for() {  # wait_for TIMEOUT PATTERN WATCH_RESETS
  local t="$1" pat="$2" watch="$3" last="" raw node conn line resets=0
  for i in $(seq 1 $((t / 3))); do
    raw="$(ctl_raw)"                                 # ONE snapshot per poll
    node="$(head -1 <<<"$raw")"
    conn="$(grep -E '^(Connected|Connecting|Reconnecting|Disconnecting|Waiting to connect) ' <<<"$raw" | head -1)"
    line="${node:-<no answer>}${conn:+  |  $conn}"
    [ "$line" != "$last" ] && printf '    [%3ds] %s\n' $((i * 3)) "$line"
    printf '%s\n%s\n' "$node" "$conn" | grep -qE "$pat" && return 0
    if [ "$watch" = 1 ] && echo "$last" | grep -q '^Ready' && echo "$node" | grep -qE '^(Initializing|Warmup|Worker)'; then
      resets=$((resets + 1))
      if [ "$resets" -ge 2 ]; then
        say "the node RESET $resets times after connect -- stopping"
        echo "    Falling from Ready back to Warmup/Initializing is the client rebuilding its"
        echo "    node, not a slow connect. Its own errors since the count began:"
        log_errors
        echo "    Compare: sudo ./bench/use-arm.sh auto --count   (does the control do this too?)"
        return 1
      fi
    fi
    last="$line"; sleep 3
  done
  echo "    gave up after ${t}s (last: ${last:-<none>})" >&2
  log_errors
  return 1
}

log_from=$(stat -c %s "$GVPN_SERVICE_LOG" 2>/dev/null || echo 0)
"$CTL" start-client 60m >/dev/null 2>&1 || true
wait_for "$READY_TIMEOUT" '^(Ready|Connected)' 0 || exit 1

# Show what connect itself says -- "Unable to connect to UK: <route health>"
# or "Waiting to connect ... once possible" is the answer, not a detail.
echo "    connect: $("$CTL" connect "$DEST" 2>&1 | head -2 | tr '\n' ' ')"
wait_for "$CONNECT_TIMEOUT" "^Connected to $DEST " 1 || { "$CTL" disconnect >/dev/null 2>&1 || true; exit 1; }

echo "    connected; pulling traffic for ${SETTLE}s"
url="${GVPN_DL_URL:-https://speed.cloudflare.com/__down?bytes={bytes}}"
curl -s -o /dev/null --max-time "$SETTLE" "${url//\{bytes\}/2000000000}" || true
"$CTL" disconnect >/dev/null 2>&1 || true

r="$(python3 "$GVPN_KIT/lib/routes.py" "$GVPN_SERVICE_LOG" --from-byte "$log_from")"
get() { printf '%s\n' "$r" | tr ' ' '\n' | sed -n "s/^$1=//p"; }

if [ "$(get lines)" -eq 0 ]; then
  say "NO RESULT: the planner logged no candidate paths"
  echo "    Not the same as 1 route -- nothing was counted. Planner DEBUG is off:"
  echo "    sudo ./setup/00-vm-setup.sh   then re-run this"
  exit 1
fi
say "RESULT: '$ARM' candidates=$(get candidates)   (forward $(get forward), return $(get return))"
echo "    churn: $(get churn) distinct paths over the window, $(get rebuilds) cache rebuilds, $(get lines) lines"
echo
echo "    candidates = the set each draw picks from; 1 means one path at a time (no striping)."
echo "    churn      = how often a refresh switched path; it can exceed 1 even when pinned."
echo "    expected:  pin-planner candidates = 1;  auto > 1 (on jura, capped at 3)."
