#!/usr/bin/env bash
#
# use-arm.sh -- install one arm by hand; optionally connect and count routes.
#
#   sudo ./bench/use-arm.sh auto --count         # must read many routes
#   sudo ./bench/use-arm.sh pin-planner --count  # must read 1
#   sudo ./bench/use-arm.sh --show               # what is installed now
#   sudo ./bench/use-arm.sh --restore            # back to the network config
#
# Installing an arm = write its config to config-gvpn-arm.toml and re-point the
# config.toml symlink (lib/common.sh). If the service then fails to start, the
# original network config is put back and the service restarted, so this never
# leaves the node down.
set -euo pipefail
. "$(cd "$(dirname "$0")/.." && pwd)/lib/common.sh"

CTL="${GVPN_CTL:-gnosis_vpn-ctl}"
DEST="${GVPN_DESTINATION:-UK}"
SETTLE="${GVPN_COUNT_SETTLE:-90}"
READY_TIMEOUT=180; CONNECT_TIMEOUT=180
LEGACY="/etc/systemd/system/gnosisvpn.service.d/30-arm.conf /etc/gnosisvpn/hopr-arm.yaml"

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
ctl_status() { timeout 10 "$CTL" -o plain status 2>/dev/null | head -1; }

show() {
  echo "  config.toml -> $(readlink -f "$GVPN_CONFIG_PATH")"
  head -1 "$GVPN_CONFIG_PATH" 2>/dev/null | grep -q 'GENERATED by gvpn-8408' \
    && sed -n '1s/.*-- /  arm:        /p' "$GVPN_CONFIG_PATH" \
    || echo "  arm:        <none -- the network config>"
  echo "  planner:"
  sed -n '/^\[connection\.path_planner\]/,/^\[/p' "$GVPN_CONFIG_PATH" 2>/dev/null \
    | grep -E '^[a-z_]+ *=' | sed 's/^/    /' || echo "    <preset>"
  echo "  service:    $(systemctl is-active gnosisvpn 2>/dev/null)   client: $(ctl_status || echo '<no answer>')"
}

usage() { sed -n '3,8p' "$0" | sed 's/^# \{0,1\}//'; echo; echo "arms in $GVPN_ARMS_DIR:"; ls "$GVPN_ARMS_DIR" 2>/dev/null | sed 's/^/  /'; }

ARM=""; COUNT=0
while [ $# -gt 0 ]; do
  case "$1" in
    --count)   COUNT=1; shift ;;
    --dest)    DEST="$2"; shift 2 ;;
    --settle)  SETTLE="$2"; shift 2 ;;
    --show)    show; exit 0 ;;
    --restore) gvpn_restore_original && gvpn_service_restart && { echo "network config restored"; show; exit 0; }
               echo "could not restore -- see: sudo ./tools/diagnose.sh" >&2; exit 1 ;;
    -h|--help) usage; exit 0 ;;
    -*)        echo "unknown option: $1" >&2; exit 2 ;;
    *)         ARM="$1"; shift ;;
  esac
done
[ -n "$ARM" ] || { usage; exit 2; }
[ "$(id -u)" = 0 ] || { echo "run with sudo" >&2; exit 1; }
ARM_DIR="$GVPN_ARMS_DIR/$ARM"
[ -f "$ARM_DIR/config.toml" ] || { echo "no arm '$ARM' -- run: sudo -E ./setup/02-make-arms.sh" >&2; exit 1; }

# ----------------------------------------------------------------- install --
say "installing arm: $ARM"
sed 's/^/    /' "$ARM_DIR/README"
if [ -f "$ARM_DIR/flags" ]; then
  for f in $(cat "$ARM_DIR/flags"); do
    systemctl show gnosisvpn -p ExecStart | grep -q -- "$f" \
      || { echo "    this arm needs service flag $f -- run: sudo ./setup/00-vm-setup.sh --allow-insecure" >&2; exit 1; }
  done
fi
[ -f "$ARM_DIR/PREREQUISITE" ] && { echo; echo "    PREREQUISITE:"; sed 's/^/      /' "$ARM_DIR/PREREQUISITE"; }

"$CTL" disconnect >/dev/null 2>&1 || true
rm -f $LEGACY                                   # left by kits before the config.toml fix
gvpn_install_arm "$ARM_DIR/config.toml"
log_from=$(stat -c %s "$GVPN_SERVICE_LOG" 2>/dev/null || echo 0)

if ! gvpn_service_restart; then
  say "SERVICE DID NOT START with this arm"
  gvpn_service_why | sed 's/^/    /'
  echo "    --- service log since install ---"
  tail -c +"$((log_from + 1))" "$GVPN_SERVICE_LOG" 2>/dev/null | tail -15 | sed 's/^/    /'
  say "restoring the network config"
  gvpn_restore_original && gvpn_service_restart \
    && echo "    service is back up on the network config" \
    || echo "    STILL DOWN -- run: sudo ./tools/diagnose.sh"
  exit 1
fi
echo "    service active"
[ "$COUNT" = 1 ] || { show; exit 0; }

# ------------------------------------------------------------------- count --
# One route vs many is the check that a pin actually took. It needs planner
# DEBUG logging (00-vm-setup.sh) and traffic flowing, or there is nothing to see.
say "counting routes for '$ARM' via $DEST  (~$((SETTLE / 60 + 3)) min, one line per state change)"
grep -qE "^\[destinations\.\"?$DEST\"?\]" "$GVPN_CONFIG_PATH" \
  || { echo "    '$DEST' is not a destination in this config" >&2; exit 1; }

wait_state() {  # wait_state TIMEOUT PATTERN ACTION...
  local t="$1" pat="$2" last="" st; shift 2
  "$@" >/dev/null 2>&1 || true
  for i in $(seq 1 $((t / 3))); do
    st="$(ctl_status)"
    [ "$st" != "$last" ] && { printf '    [%3ds] %s\n' $((i * 3)) "${st:-<no answer>}"; last="$st"; }
    echo "$st" | grep -qE "$pat" && return 0
    sleep 3
  done
  echo "    gave up after ${t}s (last: ${last:-<none>})" >&2; return 1
}
log_from=$(stat -c %s "$GVPN_SERVICE_LOG" 2>/dev/null || echo 0)
wait_state "$READY_TIMEOUT"   '^(Ready|Connected)' "$CTL" start-client 60m || exit 1
wait_state "$CONNECT_TIMEOUT" "^Connected to $DEST" "$CTL" connect "$DEST" || exit 1

echo "    connected; pulling traffic for ${SETTLE}s"
url="${GVPN_DL_URL:-https://speed.cloudflare.com/__down?bytes={bytes}}"
curl -s -o /dev/null --max-time "$SETTLE" "${url//\{bytes\}/2000000000}" || true
"$CTL" disconnect >/dev/null 2>&1 || true

read -r lines paths cands < <(python3 "$GVPN_KIT/lib/routes.py" "$GVPN_SERVICE_LOG" \
    --from-byte "$log_from" | sed 's/[a-z]*=//g')

if [ "${lines:-0}" -eq 0 ]; then
  say "NO RESULT: the planner logged no candidate paths"
  echo "    Not the same as 1 route -- nothing was counted. Planner DEBUG is off:"
  echo "    sudo ./setup/00-vm-setup.sh --network <net>   then re-run this"
  exit 1
fi
routes=$(( paths > cands ? paths : cands ))     # same definition as gvpn-analyze.py
say "RESULT: '$ARM' routes=$routes   (distinct paths=$paths, max candidates=$cands, $lines lines)"
[ "$paths" = "$cands" ] || echo "    the two measures disagree -- read lib/routes.py before trusting either"
echo "    expected: pin-planner = 1, auto = many. Both many => the override is not applied."
