#!/usr/bin/env bash
#
# 02-make-arms.sh -- render arm templates (repo) into runnable arms (state dir).
#
#   sudo -E ./setup/02-make-arms.sh                      all arms, destination from gvpn.conf
#   sudo -E ./setup/02-make-arms.sh --pin-relay 0xRELAY  also the pin-cfg pair for that relay
#   ./setup/02-make-arms.sh --list
#
# A template (arms/<name>/) holds a hop count and an optional config.append
# fragment -- no addresses, so it is tracked. An instance ($GVPN_ARMS_DIR/<name>/)
# is a complete config.toml: the node's network config with the fragment MERGED
# in by lib/tomlmerge.py, which refuses to write anything that does not parse.
#
# The base is always the node's ORIGINAL network config, never an arm: config.toml
# is a symlink that use-arm.sh re-points at the active arm, so reading it blindly
# after an arm is installed would build every arm on top of the last one.
set -euo pipefail
. "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"

TEMPLATES="$GVPN_ARM_TEMPLATES"
OUT="$GVPN_ARMS_DIR"
DESTINATION="${GVPN_DESTINATION:-}"
BASE="${GVPN_BASE_CONFIG:-}"
PIN_RELAYS=()
MERGE="$GVPN_KIT/lib/tomlmerge.py"

usage() { sed -n '3,6p' "$0" | sed 's/^# \{0,1\}//'; cat <<EOF

  --destination NAME   keep only this exit (default: \$GVPN_DESTINATION = ${GVPN_DESTINATION:-all})
  --pin-relay ADDR     also render pin-cfg-<relay> and pin-cfg-pinned-<relay>; repeatable
  --base PATH          network config to derive from (default: the node's original)
  --list               show templates and exit
EOF
}

LIST=0
while [ $# -gt 0 ]; do
  case "$1" in
    --destination) DESTINATION="$2"; shift 2 ;;
    --pin-relay)   PIN_RELAYS+=("$2"); shift 2 ;;
    --base)        BASE="$2"; shift 2 ;;
    --list)        LIST=1; shift ;;
    -h|--help)     usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [ "$LIST" = 1 ]; then
  printf '%-18s %-5s %s\n' TEMPLATE HOPS SUMMARY
  for t in "$TEMPLATES"/*/; do
    printf '%-18s %-5s %s\n' "$(basename "$t")" "$(cat "$t/hops")" "$(head -1 "$t/README")"
  done
  exit 0
fi

# ------------------------------------------------------------------- base --
# The original network config: recorded by use-arm.sh on first install, else
# whatever config.toml resolves to now.
if [ -z "$BASE" ]; then
  if [ -s "$GVPN_CONFIG_ORIG" ]; then
    BASE="$(cat "$GVPN_CONFIG_ORIG")"
  else
    BASE="$(readlink -f "$GVPN_CONFIG_PATH")"
  fi
fi
[ -r "$BASE" ] || { echo "cannot read base config $BASE" >&2; exit 1; }
if grep -q '^# GENERATED by gvpn-8408' "$BASE"; then
  echo "refusing: $BASE is itself a rendered arm, not a network config." >&2
  echo "restore the node's config first: sudo ./tools/restore-config.sh --apply" >&2
  exit 1
fi
python3 "$MERGE" check "$BASE" >/dev/null || {
  echo "the node's network config does not parse -- nothing can be derived from it." >&2
  echo "repair it first: sudo ./tools/restore-config.sh --apply" >&2
  exit 1
}

gvpn_state_init
echo "base:        $BASE"
echo "instances:   $OUT"
echo "destination: ${DESTINATION:-all}"
echo

render() {  # render TEMPLATE_DIR NAME [RELAY]
  local t="$1" name="$2" relay="${3:-}" d="$OUT/$2" over="-"
  rm -rf "$d"; mkdir -p "$d"
  if [ -f "$t/config.append" ]; then
    sed "s/@RELAY@/$relay/g" "$t/config.append" > "$d/config.append"
    over="$d/config.append"
  fi
  python3 "$MERGE" render "$BASE" "$over" "$d/config.toml" --hops "$(cat "$t/hops")" \
          ${DESTINATION:+--destination "$DESTINATION"} --label "$name"
  sed "s/@RELAY@/$relay/g" "$t/README" > "$d/README"
  [ -f "$t/flags" ]        && cp "$t/flags" "$d/flags"
  [ -f "$t/PREREQUISITE" ] && sed "s/@RELAY@/$relay/g" "$t/PREREQUISITE" > "$d/PREREQUISITE"
  printf '  %-26s %s\n' "$name" "$(head -1 "$d/README")"
}

for t in "$TEMPLATES"/*/; do
  case "$(basename "$t")" in _*) continue ;; esac     # per-relay templates below
  render "$t" "$(basename "$t")"
done

for relay in "${PIN_RELAYS[@]:-}"; do
  [ -n "$relay" ] || continue
  render "$TEMPLATES/_pin-cfg"        "pin-cfg-${relay:0:10}"        "$relay"
  render "$TEMPLATES/_pin-cfg-pinned" "pin-cfg-pinned-${relay:0:10}" "$relay"
  echo "    pin-cfg needs its channels trimmed first -- see $OUT/pin-cfg-${relay:0:10}/PREREQUISITE"
done

echo
gvpn_give_back "$GVPN_ARMS_DIR"
echo "Every config above parsed and carries its arm's values. Next:"
echo "  make count ARM=auto          # candidates > 1"
echo "  make count ARM=pin-planner   # candidates = 1"
