#!/usr/bin/env bash
#
# diagnose.sh -- one read-only report on why the service is (not) running.
#
#   sudo ./tools/diagnose.sh        (or: make diagnose)
#
# Changes nothing. Addresses, keys and peer IDs are redacted, so the output is
# safe to paste.
set -uo pipefail
. "$(cd "$(dirname "$0")/.." && pwd)/lib/common.sh"

h() { printf '\n========== %s ==========\n' "$*"; }
redact() {
  sed -E -e 's/0x[0-9a-fA-F]{64}/0x<KEY>/g' -e 's/0x[0-9a-fA-F]{40}/0x<ADDR>/g' \
         -e 's/\b(12D3Koo|16Uiu2)[1-9A-HJ-NP-Za-km-z]+/<PEERID>/g'
}

h "service"
echo "state: $(systemctl is-active gnosisvpn)"
gvpn_service_why
echo
echo "The binary logs its own errors to $GVPN_SERVICE_LOG, not journald:"
errs="$(sed 's/\x1b\[[0-9;]*m//g' "$GVPN_SERVICE_LOG" 2>/dev/null | grep -aE ' (ERROR|WARN) ' | tail -8)"
[ -n "$errs" ] && printf '%s\n' "$errs" | redact || echo "  <no ERROR/WARN lines>"

h "active config"
cfg="$(readlink -f "$GVPN_CONFIG_PATH")"
echo "config.toml -> $cfg"
python3 "$GVPN_KIT/lib/tomlmerge.py" check "$cfg" 2>&1
head -1 "$cfg" | grep -q 'GENERATED by gvpn-8408' && echo "this is an ARM config: $(sed -n '1s/.*-- //p' "$cfg")"
echo "tables:"; grep -nE '^\[' "$cfg" | sed 's/^/  /'
echo "original network config recorded: $(cat "$GVPN_CONFIG_ORIG" 2>/dev/null || echo '<none>')"

h "config directory"
ls -la "$GVPN_CONFIG_DIR"
for b in "$GVPN_CONFIG_DIR"/config.toml.*backup*; do
  [ -L "$b" ] && echo ">>> $(basename "$b") is a SYMLINK, not a backup -- run tools/restore-config.sh"
done
pkg="$(dpkg -S "$cfg" 2>/dev/null | cut -d: -f1)"
[ -n "$pkg" ] && dpkg --verify "$pkg" 2>/dev/null | grep "$GVPN_CONFIG_DIR" \
  | sed 's/^/modified vs package: /'

h "unit, drop-ins, environment"
systemctl cat gnosisvpn 2>&1 | redact
pid="$(systemctl show gnosisvpn -p MainPID --value)"
if [ "${pid:-0}" != 0 ]; then
  echo "RUST_LOG in the running process: $(tr '\0' '\n' < /proc/$pid/environ | sed -n 's/^RUST_LOG=//p')"
else
  echo "RUST_LOG that would apply (last EnvironmentFile wins):"
  systemctl show gnosisvpn -p EnvironmentFiles --value | tr ' ' '\n' | grep '^/' \
    | while read -r f; do grep -H '^RUST_LOG=' "$f" 2>/dev/null; done
fi

h "routing"
ip -4 -o addr show scope global | awk '{print "address:", $2, $4}'
echo "main table:"; ip -4 route show table main | sed 's/^/  /'
echo "table 200 (SSH bypass):"; ip -4 route show table 200 2>/dev/null | sed 's/^/  /' | grep . || echo "  <EMPTY -- SSH is not protected>"
echo "rules:"; ip rule show | sed 's/^/  /'
if gvpn_gateway_ok; then
  echo "gateway probe: the kernel accepts '/32 via <gateway>' -- client bypass routes will work"
else
  echo "gateway probe: the kernel REFUSES '/32 via <gateway>' (not on-link) -- every connect fails"
  echo "               fix: sudo ./setup/00-vm-setup.sh"
fi

h "identity"
ls -la /var/lib/gnosisvpn/.config 2>&1 | redact

h "journal (systemd's view)"
journalctl -u gnosisvpn -n 10 --no-pager 2>&1 | redact

h "packages"
dpkg-query -W -f='${Package} ${Version}\n' 'gnosis*' 2>/dev/null
echo; echo "End of report. Nothing was changed."
